# Packages and apps for macOS.

tap "oven-sh/bun", trusted: true
tap "steipete/tap", trusted: true

brew "antidote"
brew "bash"
brew "buf"
brew "chezmoi"
brew "cloud-sql-proxy"
brew "gh"
brew "git"
brew "gnupg"
brew "herdr"
brew "node@24"
brew "openjdk"
brew "openjdk@11"
brew "oven-sh/bun/bun"
brew "pinentry-mac"
brew "pnpm"
brew "redis"
brew "ruby"
brew "starship"
brew "webp"
brew "zsh"

cask "adobe-creative-cloud"
cask "android-studio"
cask "caskhub"
cask "cyberduck"
cask "docker-desktop"
cask "figma"
cask "firefox"
cask "font-fira-code"
cask "gcloud-cli"
cask "ghostty"
cask "git-credential-manager"
cask "google-chrome"
cask "google-drive"
cask "keepingyouawake"
cask "kreya"
cask "raspberry-pi-imager"
cask "rive"
cask "tablepro"
cask "zed"
